# Generated by Django 4.2 on 2023-08-16 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_type', models.CharField(max_length=100)),
                ('Details', models.CharField(max_length=100)),
                ('Price_per_day', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Proof', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=100)),
                ('ReturnDate', models.CharField(max_length=20)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.product')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.user'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=300)),
                ('Date', models.CharField(max_length=20)),
                ('Reply', models.CharField(max_length=300)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chat', models.CharField(max_length=300)),
                ('Date', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=20)),
                ('From_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='RentalApp.user')),
                ('To_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to='RentalApp.user')),
            ],
        ),
    ]
