# Generated by Django 3.2.20 on 2023-10-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0003_alter_user_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='Chat',
            new_name='Chat1',
        ),
    ]
